spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none # @Entity? jpa? ??? ?? ?? -> schema.sql ??? ? ??(?? ??? none ??)
    database-platform: org.hibernate.dialect.H2Dialect
    #defer-datasource-initialization: true -> jpa ???? schema.sql, data.sql ?? ??


  sql:
    init:
      mode: always
      platform: h2

  datasource:
    url: jdbc:h2:mem:development;MODE=MYSQL;DB_CLOSE_DELAY=-1 # jdbc:h2:file:./data/mydb -> ???db? ?? ??? ??
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console