INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, DUE_DATE)
VALUES ('백준', '실버1문제 풀기', 'IN_PROGRESS', DATEADD('DAY', 1, NOW()));

INSERT INTO TASK (TITLE, DESCRIPTION, STATUS, DUE_DATE)
VALUES ('백준', '실버2문제 풀기', 'TODO', DATEADD('DAY', 2, NOW()));


